[package]
name = "pola"
version = "0.1.0"
edition = "2024"

[dependencies]
global-hotkey = "0.8.0"
jiff = { version = "0.2.37", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
toml = "1.1.6"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.4"
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["NSAlert", "NSApplication", "NSAppearance", "NSButton", "NSMenu", "NSOpenPanel", "NSPopUpButton", "NSScreen", "NSScrollView", "NSStatusBar", "NSTabView", "NSTextField", "NSView", "NSWindow", "NSWorkspace", "NSCell", "NSControl", "NSMenuItem", "NSPanel", "NSResponder", "NSSavePanel", "NSStatusItem", "NSTabViewItem", "AppKitDefines", "NSClipView", "NSGraphics", "NSRunningApplication", "NSStatusBarButton", "objc2-core-foundation"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["NSAppleScript", "NSArray", "NSDictionary", "NSDistributedNotificationCenter", "NSNotification", "NSTimer", "NSURL", "NSString", "NSObject", "NSEnumerator", "NSTimeZone"] }
